[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=10.160.0.0/16
external_media_address=8.234.82.172
external_signaling_address=8.234.82.172

[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/certs/asterisk.crt
priv_key_file=/etc/asterisk/certs/asterisk.key
method=unspecified
verify_client=no
verify_server=no
local_net=10.160.0.0/16
external_media_address=8.234.82.172
external_signaling_address=8.234.82.172

[whatsapp-endpoint]
type=endpoint
context=whatsapp-inbound
transport=transport-tls
disallow=all
allow=alaw
allow=ulaw
allow=slin16
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_encryption=sdes

[whatsapp-identify]
type=identify
endpoint=whatsapp-endpoint
match=0.0.0.0/0
